# Generated by Django 4.1.1 on 2022-09-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
